####

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "username": "UniqueName",
    "password": "123"
}

###

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "UniqueName",
    "password": "123"
}
###

POST http://localhost:4000/api/createGroup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYwMjJhYzJmZWU1NGJmNmVmYjMzNWUiLCJ1c2VybmFtZSI6IlVuaXF1ZU5hbWUiLCJpYXQiOjE3MTAyNDc4ODMsImV4cCI6MTcxMDMzNDI4M30.RIv1ci7CNNs8NkNMy67EWklVLC5IuMewfay4zmb-JVg

{
    "groupName": "newGroup"
}