####

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "username": "1",
    "password": "1"
}

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYxYWFmNzNhMjY2ZDkyMzNhZjE4ZjEiLCJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcxMDMzNjc1OSwiZXhwIjoxNzEwNDIzMTU5fQ.v55KJsbwICvY2kg6o1R3hYmyHnp4zZoX67a_yBlUN1I

POST http://localhost/api/login
Content-Type: application/json

{
    "username": "MsgTest",
    "password": "123"
}
###

POST http://localhost:4000/api/createGroup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYwN2QzMjQ2ZGM5N2NhMjNhOGQzMTMiLCJ1c2VybmFtZSI6Ik1zZ1Rlc3QiLCJpYXQiOjE3MTAyNTk1MDYsImV4cCI6MTcxMDM0NTkwNn0.uZPFkmapryZxeLqvSq9KvYjxGRhnZA3AEeV9qfPB6OY

{
    "groupName": "k"
}

###

POST http://localhost:4000/api/addGroupMember
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYwN2QzMjQ2ZGM5N2NhMjNhOGQzMTMiLCJ1c2VybmFtZSI6Ik1zZ1Rlc3QiLCJpYXQiOjE3MTAyNTk1MDYsImV4cCI6MTcxMDM0NTkwNn0.uZPFkmapryZxeLqvSq9KvYjxGRhnZA3AEeV9qfPB6OY

{
    "groupId": "65f07d5546dc97ca23a8d316",
    "userIdToAdd": "65f0795dd1bade7f77058e21"
}

###

GET http://localhost/api/getGroups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYwN2QzMjQ2ZGM5N2NhMjNhOGQzMTMiLCJ1c2VybmFtZSI6Ik1zZ1Rlc3QiLCJpYXQiOjE3MTEzOTAwODUsImV4cCI6MTcxMTQ3NjQ4NX0.5P6CXS12waxP7hCUmPDRxtQxpjBn9z0vd14OX-1AkY0

###
GET http://localhost:4000/api/groups/65f1b3a53a266d9233af18ff/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYxYWFmNzNhMjY2ZDkyMzNhZjE4ZjEiLCJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcxMDMzNjc1OSwiZXhwIjoxNzEwNDIzMTU5fQ.v55KJsbwICvY2kg6o1R3hYmyHnp4zZoX67a_yBlUN1I

###
GET http://localhost:4000/api/getUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYwN2QzMjQ2ZGM5N2NhMjNhOGQzMTMiLCJ1c2VybmFtZSI6Ik1zZ1Rlc3QiLCJpYXQiOjE3MTAyNjE1OTMsImV4cCI6MTcxMDM0Nzk5M30.ggl_zLHne38byoj3H7ilgfbw0CWu24lIME4sP2LP4To

####
POST http://localhost:4000/api/directChat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYwN2QzMjQ2ZGM5N2NhMjNhOGQzMTMiLCJ1c2VybmFtZSI6Ik1zZ1Rlc3QiLCJpYXQiOjE3MTAyNTk1MDYsImV4cCI6MTcxMDM0NTkwNn0.uZPFkmapryZxeLqvSq9KvYjxGRhnZA3AEeV9qfPB6OY

{
    "partnerId": "65e718918531617eb9aca4eb"
}